language: python
python:
  - "3.8"
  - "3.9"
install:
  - pip install -e .[develop]
  # - pip install coveralls
script:
  - pre-commit run --all-files
  - python setup.py test
  # - coverage run --source financeager_flask setup.py test
# after_success:
#   - coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
